<?php

// Flat icons
function saasland_flaticons() {
    return [
        'flaticon-target' => 'Target',
        'flaticon-lightbulb' => 'Light Bulb',
        'flaticon-mortarboard' => 'Mortar Board',
    ];
}

function saasland_include_flaticons() {
    return array_keys(saasland_flaticons());
}


/**
 * Simple Line Icon Library
 * @return array
 */
function saasland_simple_line_icons() {
    $simple_line_icons = [
        'icon-user',
        'icon-people',
        'icon-user-female',
        'icon-user-follow',
        'icon-user-following',
        'icon-user-unfollow',
        'icon-login',
        'icon-logout',
        'icon-emotsmile',
        'icon-phone',
        'icon-call-end',
        'icon-call-in',
        'icon-call-out',
        'icon-map',
        'icon-location-pin',
        'icon-direction',
        'icon-directions',
        'icon-compass',
        'icon-layers',
        'icon-menu',
        'icon-list',
        'icon-options-vertica',
        'icon-options',
        'icon-arrow-down',
        'icon-arrow-left',
        'icon-arrow-right',
        'icon-arrow-up',
        'icon-arrow-up-circle',
        'icon-arrow-left-circ',
        'icon-arrow-right-cir',
        'icon-arrow-down-circ',
        'icon-check',
        'icon-clock',
        'icon-plus',
        'icon-minus',
        'icon-close',
        'icon-event',
        'icon-exclamation',
        'icon-organization',
        'icon-trophy',
        'icon-screen-smartpho',
        'icon-screen-desktop',
        'icon-plane',
        'icon-notebook',
        'icon-mustache',
        'icon-mouse',
        'icon-magnet',
        'icon-energy',
        'icon-disc',
        'icon-cursor',
        'icon-cursor-move',
        'icon-crop',
        'icon-chemistry',
        'icon-speedometer',
        'icon-shield',
        'icon-screen-tablet',
        'icon-magic-wand',
        'icon-hourglass',
        'icon-graduation',
        'icon-ghost',
        'icon-game-controller',
        'icon-fire',
        'icon-eyeglass',
        'icon-envelope-open',
        'icon-envelope-letter',
        'icon-bell',
        'icon-badge',
        'icon-anchor',
        'icon-wallet',
        'icon-vector',
        'icon-speech',
        'icon-puzzle',
        'icon-printer',
        'icon-present',
        'icon-playlist',
        'icon-pin',
        'icon-picture',
        'icon-handbag',
        'icon-globe-alt',
        'icon-globe',
        'icon-folder-alt',
        'icon-folder',
        'icon-film',
        'icon-feed',
        'icon-drop',
        'icon-drawer',
        'icon-docs',
        'icon-doc',
        'icon-diamond',
        'icon-cup',
        'icon-calculator',
        'icon-bubbles',
        'icon-briefcase',
        'icon-book-open',
        'icon-basket-loaded',
        'icon-basket',
        'icon-bag',
        'icon-action-undo',
        'icon-action-redo',
        'icon-wrench',
        'icon-umbrella',
        'icon-trash',
        'icon-tag',
        'icon-support',
        'icon-frame',
        'icon-size-fullscreen',
        'icon-size-actual',
        'icon-shuffle',
        'icon-share-alt',
        'icon-share',
        'icon-rocket',
        'icon-question',
        'icon-pie-chart',
        'icon-pencil',
        'icon-note',
        'icon-loop',
        'icon-home',
        'icon-grid',
        'icon-graph',
        'icon-microphone',
        'icon-music-tone-alt',
        'icon-music-tone',
        'icon-earphones-alt',
        'icon-earphones',
        'icon-equalizer',
        'icon-like',
        'icon-dislike',
        'icon-control-start',
        'icon-control-rewind',
        'icon-control-play',
        'icon-control-pause',
        'icon-control-forward',
        'icon-control-end',
        'icon-volume-1',
        'icon-volume-2',
        'icon-volume-off',
        'icon-calendar',
        'icon-bulb',
        'icon-chart',
        'icon-ban',
        'icon-bubble',
        'icon-camrecorder',
        'icon-camera',
        'icon-cloud-download',
        'icon-cloud-upload',
        'icon-envelope',
        'icon-eye',
        'icon-flag',
        'icon-heart',
        'icon-info',
        'icon-key',
        'icon-link',
        'icon-lock',
        'icon-lock-open',
        'icon-magnifier',
        'icon-magnifier-add',
        'icon-magnifier-remove',
        'icon-paper-clip',
        'icon-paper-plane',
        'icon-power',
        'icon-refresh',
        'icon-reload',
        'icon-settings',
        'icon-star',
        'icon-symbol-female',
        'icon-symbol-male',
        'icon-target',
        'icon-credit-card',
        'icon-paypal',
        'icon-social-tumblr',
        'icon-social-twitter',
        'icon-social-facebook',
        'icon-social-instagram',
        'icon-social-linkedin',
        'icon-social-pinterest',
        'icon-social-github',
        'icon-social-google',
        'icon-social-reddit',
        'icon-social-skype',
        'icon-social-dribbble',
        'icon-social-behance',
        'icon-social-foursqare',
        'icon-social-soundclou',
        'icon-social-spotify',
        'icon-social-stumbleup',
        'icon-social-youtube',
        'icon-social-dropbox',
        'icon-social-vkontakte',
    ];
    return saasland_icon_array($simple_line_icons);
}

function saasland_include_simple_line_icons() {
    return array_keys(saasland_simple_line_icons());
}


/**
 * Elegant Icons
 */
function saasland_elegant_icons() {
    $et_icons = 'arrow_up, arrow_down, arrow_left, arrow_right, arrow_left-up, arrow_right-up, arrow_right-down, arrow_left-down, arrow-up-down, arrow_up-down_alt, arrow_left-right_alt, arrow_left-right, arrow_expand_alt2, arrow_expand_alt, arrow_condense, arrow_expand, arrow_move, arrow_carrot-up, arrow_carrot-down, arrow_carrot-left, arrow_carrot-right, arrow_carrot-2up, arrow_carrot-2down, arrow_carrot-2left, arrow_carrot-2right, arrow_carrot-up_alt2, arrow_carrot-down_alt2, arrow_carrot-left_alt2, arrow_carrot-right_alt2, arrow_carrot-2up_alt2, arrow_carrot-2down_alt2, arrow_carrot-2left_alt2, arrow_carrot-2right_alt2, arrow_triangle-up, arrow_triangle-down, arrow_triangle-left, arrow_triangle-right, arrow_triangle-up_alt2, arrow_triangle-down_alt2, arrow_triangle-left_alt2, arrow_triangle-right_alt2, arrow_back, icon_minus-06, icon_plus, icon_close, icon_check, icon_minus_alt2, icon_plus_alt2, icon_close_alt2, icon_check_alt2, icon_zoom-out_alt, icon_zoom-in_alt, icon_search, icon_box-empty, icon_box-selected, icon_minus-box, icon_plus-box, icon_box-checked, icon_circle-empty, icon_circle-slelected, icon_stop_alt2, icon_stop, icon_pause_alt2, icon_pause, icon_menu, icon_menu-square_alt2, icon_menu-circle_alt2, icon_ul, icon_ol, icon_adjust-horiz, icon_adjust-vert, icon_document_alt, icon_documents_alt, icon_pencil, icon_pencil-edit_alt, icon_pencil-edit, icon_folder-alt, icon_folder-open_alt, icon_folder-add_alt, icon_info_alt, icon_error-oct_alt, icon_error-circle_alt, icon_error-triangle_alt, icon_question_alt2, icon_question, icon_comment_alt, icon_chat_alt, icon_vol-mute_alt, icon_volume-low_alt, icon_volume-high_alt, icon_quotations, icon_quotations_alt2, icon_clock_alt, icon_lock_alt, icon_lock-open_alt, icon_key_alt, icon_cloud_alt, icon_cloud-upload_alt, icon_cloud-download_alt, icon_image, icon_images, icon_lightbulb_alt, icon_gift_alt, icon_house_alt, icon_genius, icon_mobile, icon_tablet, icon_laptop, icon_desktop, icon_camera_alt, icon_mail_alt, icon_cone_alt, icon_ribbon_alt, icon_bag_alt, icon_creditcard, icon_cart_alt, icon_paperclip, icon_tag_alt, icon_tags_alt, icon_trash_alt, icon_cursor_alt, icon_mic_alt, icon_compass_alt, icon_pin_alt, icon_pushpin_alt, icon_map_alt, icon_drawer_alt, icon_toolbox_alt, icon_book_alt, icon_calendar, icon_film, icon_table, icon_contacts_alt, icon_headphones, icon_lifesaver, icon_piechart, icon_refresh, icon_link_alt, icon_link, icon_loading, icon_blocked, icon_archive_alt, icon_heart_alt, icon_star_alt, icon_star-half_alt, icon_star, icon_star-half, icon_tools, icon_tool, icon_cog, icon_cogs, arrow_up_alt, arrow_down_alt, arrow_left_alt, arrow_right_alt, arrow_left-up_alt, arrow_right-up_alt, arrow_right-down_alt, arrow_left-down_alt, arrow_condense_alt, arrow_expand_alt3, arrow_carrot_up_alt, arrow_carrot-down_alt, arrow_carrot-left_alt, arrow_carrot-right_alt, arrow_carrot-2up_alt, arrow_carrot-2dwnn_alt, arrow_carrot-2left_alt, arrow_carrot-2right_alt, arrow_triangle-up_alt, arrow_triangle-down_alt, arrow_triangle-left_alt, arrow_triangle-right_alt, icon_minus_alt, icon_plus_alt, icon_close_alt, icon_check_alt, icon_zoom-out, icon_zoom-in, icon_stop_alt, icon_menu-square_alt, icon_menu-circle_alt, icon_document, icon_documents, icon_pencil_alt, icon_folder, icon_folder-open, icon_folder-add, icon_folder_upload, icon_folder_download, icon_info, icon_error-circle, icon_error-oct, icon_error-triangle, icon_question_alt, icon_comment, icon_chat, icon_vol-mute, icon_volume-low, icon_volume-high, icon_quotations_alt, icon_clock, icon_lock, icon_lock-open, icon_key, icon_cloud, icon_cloud-upload, icon_cloud-download, icon_lightbulb, icon_gift, icon_house, icon_camera, icon_mail, icon_cone, icon_ribbon, icon_bag, icon_cart, icon_tag, icon_tags, icon_trash, icon_cursor, icon_mic, icon_compass, icon_pin, icon_pushpin, icon_map, icon_drawer, icon_toolbox, icon_book, icon_contacts, icon_archive, icon_heart, icon_profile, icon_group, icon_grid-2x2, icon_grid-3x3, icon_music, icon_pause_alt, icon_phone, icon_upload, icon_download, social_facebook, social_twitter, social_pinterest, social_googleplus, social_tumblr, social_tumbleupon, social_wordpress, social_instagram, social_dribbble, social_vimeo, social_linkedin, social_rss, social_deviantart, social_share, social_myspace, social_skype, social_youtube, social_picassa, social_googledrive, social_flickr, social_blogger, social_spotify, social_delicious, social_facebook_circle, social_twitter_circle, social_pinterest_circle, social_googleplus_circle, social_tumblr_circle, social_stumbleupon_circle, social_wordpress_circle, social_instagram_circle, social_dribbble_circle, social_vimeo_circle, social_linkedin_circle, social_rss_circle, social_deviantart_circle, social_share_circle, social_myspace_circle, social_skype_circle, social_youtube_circle, social_picassa_circle, social_googledrive_alt2, social_flickr_circle, social_blogger_circle, social_spotify_circle, social_delicious_circle, social_facebook_square, social_twitter_square, social_pinterest_square, social_googleplus_square, social_tumblr_square, social_stumbleupon_square, social_wordpress_square, social_instagram_square, social_dribbble_square, social_vimeo_square, social_linkedin_square, social_rss_square, social_deviantart_square, social_share_square, social_myspace_square, social_skype_square, social_youtube_square, social_picassa_square, social_googledrive_square, social_flickr_square, social_blogger_square, social_spotify_square, social_delicious_square, icon_printer, icon_calulator, icon_building, icon_floppy, icon_drive, icon_search-2, icon_id, icon_id-2, icon_puzzle, icon_like, icon_dislike, icon_mug, icon_currency, icon_wallet, icon_pens, icon_easel, icon_flowchart, icon_datareport, icon_briefcase, icon_shield, icon_percent, icon_globe, icon_globe-2, icon_target, icon_hourglass, icon_balance, icon_rook, icon_printer-alt, icon_calculator_alt, icon_building_alt, icon_floppy_alt, icon_drive_alt, icon_search_alt, icon_id_alt, icon_id-2_alt, icon_puzzle_alt, icon_like_alt, icon_dislike_alt, icon_mug_alt, icon_currency_alt, icon_wallet_alt, icon_pens_alt, icon_easel_alt, icon_flowchart_alt, icon_datareport_alt, icon_briefcase_alt, icon_shield_alt, icon_percent_alt, icon_globe_alt, icon_clipboard';
    $et_icons = explode( ', ', $et_icons);
    return saasland_icon_array($et_icons, '', '_');
}

function saasland_include_elegant_icons() {
    return array_keys(saasland_elegant_icons());
}


/**
 * Themify Icon Library
 * @return array
 */
function saasland_themify_icons() {
    return [
        'ti-wand' => esc_html__( 'Wand', 'appart-core'),
        'ti-volume' => esc_html__( 'Volume', 'appart-core'),
        'ti-user' => esc_html__( 'User', 'appart-core'),
        'ti-unlock' => esc_html__( 'Unlock', 'appart-core'),
        'ti-unlink' => esc_html__( 'Unlink', 'appart-core'),
        'ti-trash' => esc_html__( 'Trash', 'appart-core'),
        'ti-thought' => esc_html__( 'Thought', 'appart-core'),
        'ti-target' => esc_html__( 'Target', 'appart-core'),
        'ti-tag' => esc_html__( 'Tag', 'appart-core'),
        'ti-tablet' => esc_html__( 'Tablet', 'appart-core'),
        'ti-star' => esc_html__( 'Star', 'appart-core'),
        'ti-spray' => esc_html__( 'Spray', 'appart-core'),
        'ti-shopping-cart-full' => esc_html__( 'Shopping Cart Full', 'appart-core'),
        'ti-shopping-cart' => esc_html__( 'Shopping Cart', 'appart-core'),
        'ti-settings' => esc_html__( 'Settings', 'appart-core'),
        'ti-search' => esc_html__( 'Search', 'appart-core'),
        'ti-zoom-in' => esc_html__( 'Zoom In', 'appart-core'),
        'ti-zoom-out' => esc_html__( 'Zoom Out', 'appart-core'),
        'ti-cut' => esc_html__( 'Cut', 'appart-core'),
        'ti-ruler' => esc_html__( 'Ruler', 'appart-core'),
        'ti-ruler-pencil' => esc_html__( 'Ruler Pencil', 'appart-core'),
        'ti-ruler-alt' => esc_html__( 'Ruler alt', 'appart-core'),
        'ti-bookmark' => esc_html__( 'Bookmark', 'appart-core'),
        'ti-bookmark-alt' => esc_html__( 'Bookmark Alt', 'appart-core'),
        'ti-reload' => esc_html__( 'Reload', 'appart-core'),
        'ti-plus' => esc_html__( 'Plus', 'appart-core'),
        'ti-pin' => esc_html__( 'Pin', 'appart-core'),
        'ti-pencil' => esc_html__( 'Pencil', 'appart-core'),
        'ti-pencil-alt' => esc_html__( 'Pencil Alt', 'appart-core'),
        'ti-paint-roller' => esc_html__( 'Paint Roller', 'appart-core'),
        'ti-paint-bucket' => esc_html__( 'Paint Bucket', 'appart-core'),
        'ti-na' => esc_html__( 'Na', 'appart-core'),
        'ti-mobile' => esc_html__( 'Mobile', 'appart-core'),
        'ti-minus' => esc_html__( 'Minus', 'appart-core'),
        'ti-medall' => esc_html__( 'Medall', 'appart-core'),
        'ti-medall-alt' => esc_html__( 'Medall Alt', 'appart-core'),
        'ti-marker' => esc_html__( 'Marker', 'appart-core'),
        'ti-marker-alt' => esc_html__( 'Marker Alt', 'appart-core'),
        'ti-arrow-up' => esc_html__( 'Arrow Up', 'appart-core'),
        'ti-arrow-right' => esc_html__( 'Arrow Right', 'appart-core'),
        'ti-arrow-left' => esc_html__( 'Arrow Left', 'appart-core'),
        'ti-arrow-down' => esc_html__( 'Arrow Down', 'appart-core'),
        'ti-lock' => esc_html__( 'Lock', 'appart-core'),
        'ti-location-arrow' => esc_html__( 'Location Arrow', 'appart-core'),
        'ti-link' => esc_html__( 'Link', 'appart-core'),
        'ti-layout' => esc_html__( 'Layout', 'appart-core'),
        'ti-layers' => esc_html__( 'Layers', 'appart-core'),
        'ti-layers-alt' => esc_html__( 'Layers Alt', 'appart-core'),
        'ti-key' => esc_html__( 'Key', 'appart-core'),
        'ti-import' => esc_html__( 'Import', 'appart-core'),
        'ti-image' => esc_html__( 'Image', 'appart-core'),
        'ti-heart' => esc_html__( 'Heart', 'appart-core'),
        'ti-heart-broken' => esc_html__( 'Heart Broken', 'appart-core'),
        'ti-hand-stop' => esc_html__( 'Hand Stop', 'appart-core'),
        'ti-hand-open' => esc_html__( 'Hand Open', 'appart-core'),
        'ti-hand-drag' => esc_html__( 'Hand Drag', 'appart-core'),
        'ti-folder' => esc_html__( 'Folder', 'appart-core'),
        'ti-flag' => esc_html__( 'Flag', 'appart-core'),
        'ti-flag-alt' => esc_html__( 'Flag Alt', 'appart-core'),
        'ti-flag-alt-2' => esc_html__( 'Flag Alt 2', 'appart-core'),
        'ti-eye' => esc_html__( 'Eye', 'appart-core'),
        'ti-export' => esc_html__( 'Export', 'appart-core'),
        'ti-exchange-vertical' => esc_html__( 'Exchange Vertical', 'appart-core'),
        'ti-desktop' => esc_html__( 'Desktop', 'appart-core'),
        'ti-cup' => esc_html__( 'Cup', 'appart-core'),
        'ti-crown' => esc_html__( 'Crown', 'appart-core'),
        'ti-comments' => esc_html__( 'Comments', 'appart-core'),
        'ti-comment' => esc_html__( 'Comment', 'appart-core'),
        'ti-comment-alt' => esc_html__( 'Comment Alt', 'appart-core'),
        'ti-close' => esc_html__( 'Close', 'appart-core'),
        'ti-clip' => esc_html__( 'Clip', 'appart-core'),
        'ti-angle-up' => esc_html__( 'Angle Up', 'appart-core'),
        'ti-angle-right' => esc_html__( 'Angle Right', 'appart-core'),
        'ti-angle-left' => esc_html__( 'Angle Left', 'appart-core'),
        'ti-angle-down' => esc_html__( 'Angle Down', 'appart-core'),
        'ti-check' => esc_html__( 'Check', 'appart-core'),
        'ti-check-box' => esc_html__( 'Check Box', 'appart-core'),
        'ti-camera' => esc_html__( 'Camera', 'appart-core'),
        'ti-announcement' => esc_html__( 'Announcement', 'appart-core'),
        'ti-brush' => esc_html__( 'Brush', 'appart-core'),
        'ti-briefcase' => esc_html__( 'Briefcase', 'appart-core'),
        'ti-bolt' => esc_html__( 'Bolt', 'appart-core'),
        'ti-bolt-alt' => esc_html__( 'Bolt Alt', 'appart-core'),
        'ti-blackboard' => esc_html__( 'Blackboard', 'appart-core'),
        'ti-bag' => esc_html__( 'Bag', 'appart-core'),
        'ti-move' => esc_html__( 'Move', 'appart-core'),
        'ti-arrows-vertical' => esc_html__( 'Arrows Vertical', 'appart-core'),
        'ti-arrows-horizontal' => esc_html__( 'Arrows Horizontal', 'appart-core'),
        'ti-fullscreen' => esc_html__( 'Fullscreen', 'appart-core'),
        'ti-arrow-top-right' => esc_html__( 'Arrow Top Right', 'appart-core'),
        'ti-arrow-top-left' => esc_html__( 'Arrow Top Left', 'appart-core'),
        'ti-arrow-circle-up' => esc_html__( 'Arrow Circle Up', 'appart-core'),
        'ti-arrow-circle-right' => esc_html__( 'Arrow Circle Right', 'appart-core'),
        'ti-arrow-circle-left' => esc_html__( 'Arrow Circle Left', 'appart-core'),
        'ti-arrow-circle-down' => esc_html__( 'Arrow Circle Down', 'appart-core'),
        'ti-angle-double-up' => esc_html__( 'Angle Double Up', 'appart-core'),
        'ti-angle-double-right' => esc_html__( 'Angle Double Right', 'appart-core'),
        'ti-angle-double-left' => esc_html__( 'Angle Double Left', 'appart-core'),
        'ti-angle-double-down' => esc_html__( 'Angle Double Down', 'appart-core'),
        'ti-zip' => esc_html__( 'Zip', 'appart-core'),
        'ti-world' => esc_html__( 'World', 'appart-core'),
        'ti-wheelchair' => esc_html__( 'Wheelchair', 'appart-core'),
        'ti-view-list' => esc_html__( 'View List', 'appart-core'),
        'ti-view-list-alt' => esc_html__( 'View List Alt', 'appart-core'),
        'ti-view-grid' => esc_html__( 'View Grid', 'appart-core'),
        'ti-uppercase' => esc_html__( 'Uppercase', 'appart-core'),
        'ti-upload' => esc_html__( 'Upload', 'appart-core'),
        'ti-underline' => esc_html__( 'Underline', 'appart-core'),
        'ti-truck' => esc_html__( 'Truck', 'appart-core'),
        'ti-timer' => esc_html__( 'Timer', 'appart-core'),
        'ti-ticket' => esc_html__( 'Ticket', 'appart-core'),
        'ti-thumb-up' => esc_html__( 'Thumb Up', 'appart-core'),
        'ti-thumb-down' => esc_html__( 'Thumb Down', 'appart-core'),
        'ti-text' => esc_html__( 'Text', 'appart-core'),
        'ti-stats-up' => esc_html__( 'Stats Up', 'appart-core'),
        'ti-stats-down' => esc_html__( 'Stats Down', 'appart-core'),
        'ti-split-v' => esc_html__( 'Split V', 'appart-core'),
        'ti-split-h' => esc_html__( 'Split-h', 'appart-core'),
        'ti-smallcap' => esc_html__( 'Smallcap', 'appart-core'),
        'ti-shine' => esc_html__( 'Shine', 'appart-core'),
        'ti-shift-right' => esc_html__( 'Shift Right', 'appart-core'),
        'ti-shift-left' => esc_html__( 'Shift Left', 'appart-core'),
        'ti-shield' => esc_html__( 'Shield', 'appart-core'),
        'ti-notepad' => esc_html__( 'Notepad', 'appart-core'),
        'ti-server' => esc_html__( 'Server', 'appart-core'),
        'ti-quote-right' => esc_html__( 'Quote Right', 'appart-core'),
        'ti-quote-left' => esc_html__( 'Quote Left', 'appart-core'),
        'ti-pulse' => esc_html__( 'Pulse', 'appart-core'),
        'ti-printer' => esc_html__( 'Printer', 'appart-core'),
        'ti-power-off' => esc_html__( 'Power Off', 'appart-core'),
        'ti-plug' => esc_html__( 'Plug', 'appart-core'),
        'ti-pie-chart' => esc_html__( 'Pie Chart', 'appart-core'),
        'ti-paragraph' => esc_html__( 'Paragraph', 'appart-core'),
        'ti-panel' => esc_html__( 'Panel', 'appart-core'),
        'ti-package' => esc_html__( 'Package', 'appart-core'),
        'ti-music' => esc_html__( 'Music', 'appart-core'),
        'ti-music-alt' => esc_html__( 'Music Alt', 'appart-core'),
        'ti-mouse' => esc_html__( 'Mouse', 'appart-core'),
        'ti-mouse-alt' => esc_html__( 'Mouse Alt', 'appart-core'),
        'ti-money' => esc_html__( 'Money', 'appart-core'),
        'ti-microphone' => esc_html__( 'Microphone', 'appart-core'),
        'ti-menu' => esc_html__( 'Menu', 'appart-core'),
        'ti-menu-alt' => esc_html__( 'Menu Alt', 'appart-core'),
        'ti-map' => esc_html__( 'Map', 'appart-core'),
        'ti-map-alt' => esc_html__( 'Map Alt', 'appart-core'),
        'ti-loop' => esc_html__( 'Loop', 'appart-core'),
        'ti-location-pin' => esc_html__( 'Location Pin', 'appart-core'),
        'ti-list' => esc_html__( 'List', 'appart-core'),
        'ti-light-bulb' => esc_html__( 'Light Bulb', 'appart-core'),
        'ti-Italic' => esc_html__( 'Italic', 'appart-core'),
        'ti-info' => esc_html__( 'Info', 'appart-core'),
        'ti-infinite' => esc_html__( 'Infinite', 'appart-core'),
        'ti-id-badge' => esc_html__( 'Badge', 'appart-core'),
        'ti-hummer' => esc_html__( 'Hummer', 'appart-core'),
        'ti-home' => esc_html__( 'Home', 'appart-core'),
        'ti-help' => esc_html__( 'Help', 'appart-core'),
        'ti-headphone' => esc_html__( 'Headphone', 'appart-core'),
        'ti-harddrives' => esc_html__( 'Harddrives', 'appart-core'),
        'ti-harddrive' => esc_html__( 'Harddrive', 'appart-core'),
        'ti-gift' => esc_html__( 'Gift', 'appart-core'),
        'ti-game' => esc_html__( 'Game', 'appart-core'),
        'ti-filter' => esc_html__( 'Filter', 'appart-core'),
        'ti-files' => esc_html__( 'Files', 'appart-core'),
        'ti-file' => esc_html__( 'File', 'appart-core'),
        'ti-eraser' => esc_html__( 'Eraser', 'appart-core'),
        'ti-envelope' => esc_html__( 'Envelope', 'appart-core'),
        'ti-download' => esc_html__( 'Download', 'appart-core'),
        'ti-direction' => esc_html__( 'Direction', 'appart-core'),
        'ti-direction-alt' => esc_html__( 'Direction Alt', 'appart-core'),
        'ti-dashboard' => esc_html__( 'Dashboard', 'appart-core'),
        'ti-control-stop' => esc_html__( 'Control Stop', 'appart-core'),
        'ti-control-shuffle' => esc_html__( 'Control Shuffle', 'appart-core'),
        'ti-control-play' => esc_html__( 'Control Play', 'appart-core'),
        'ti-control-pause' => esc_html__( 'Control Pause', 'appart-core'),
        'ti-control-forward' => esc_html__( 'Control Forward', 'appart-core'),
        'ti-control-backward' => esc_html__( 'Control Backward', 'appart-core'),
        'ti-cloud' => esc_html__( 'Cloud', 'appart-core'),
        'ti-cloud-up' => esc_html__( 'Cloud-up', 'appart-core'),
        'ti-cloud-down' => esc_html__( 'Cloud Down', 'appart-core'),
        'ti-clipboard' => esc_html__( 'Clipboard', 'appart-core'),
        'ti-car' => esc_html__( 'Car', 'appart-core'),
        'ti-calendar' => esc_html__( 'Calendar', 'appart-core'),
        'ti-book' => esc_html__( 'Book', 'appart-core'),
        'ti-bell' => esc_html__( 'Bell', 'appart-core'),
        'ti-basketball' => esc_html__( 'Basketball', 'appart-core'),
        'ti-bar-chart' => esc_html__( 'Bar Chart', 'appart-core'),
        'ti-bar-chart-alt' => esc_html__( 'Bar Chart Alt', 'appart-core'),
        'ti-back-right' => esc_html__( 'Back Right', 'appart-core'),
        'ti-back-left' => esc_html__( 'Back Left', 'appart-core'),
        'ti-arrows-corner' => esc_html__( 'Arrows Corner', 'appart-core'),
        'ti-archive' => esc_html__( 'Archive', 'appart-core'),
        'ti-anchor' => esc_html__( 'Anchor', 'appart-core'),
        'ti-align-right' => esc_html__( 'Align Right', 'appart-core'),
        'ti-align-left' => esc_html__( 'Align Left', 'appart-core'),
        'ti-align-justify' => esc_html__( 'Align Justify', 'appart-core'),
        'ti-align-center' => esc_html__( 'Align Center', 'appart-core'),
        'ti-alert' => esc_html__( 'Alert', 'appart-core'),
        'ti-alarm-clock' => esc_html__( 'Alarm Clock', 'appart-core'),
        'ti-agenda' => esc_html__( 'Agenda', 'appart-core'),
        'ti-write' => esc_html__( 'Write', 'appart-core'),
        'ti-window' => esc_html__( 'Window', 'appart-core'),
        'ti-widgetized' => esc_html__( 'Widgetized', 'appart-core'),
        'ti-widget' => esc_html__( 'Widget', 'appart-core'),
        'ti-widget-alt' => esc_html__( 'Widget Alt', 'appart-core'),
        'ti-wallet' => esc_html__( 'Wallet', 'appart-core'),
        'ti-video-clapper' => esc_html__( 'Video Clapper', 'appart-core'),
        'ti-video-camera' => esc_html__( 'Video Camera', 'appart-core'),
        'ti-vector' => esc_html__( 'Vector', 'appart-core'),
        'ti-themify-logo' => esc_html__( 'Themify Logo', 'appart-core'),
        'ti-themify-favicon' => esc_html__( 'Themify Favicon', 'appart-core'),
        'ti-themify-favicon-alt' => esc_html__( 'Themify Favicon Alt', 'appart-core'),
        'ti-support' => esc_html__( 'Support', 'appart-core'),
        'ti-stamp' => esc_html__( 'Stamp', 'appart-core'),
        'ti-split-v-alt' => esc_html__( 'Split V Alt', 'appart-core'),
        'ti-slice' => esc_html__( 'Slice', 'appart-core'),
        'ti-shortcode' => esc_html__( 'Shortcode', 'appart-core'),
        'ti-shift-right-alt' => esc_html__( 'Shift Right Alt', 'appart-core'),
        'ti-shift-left-alt' => esc_html__( 'Shift Left Alt', 'appart-core'),
        'ti-ruler-alt-2' => esc_html__( 'Ruler Alt 2', 'appart-core'),
        'ti-receipt' => esc_html__( 'Receipt', 'appart-core'),
        'ti-pin2' => esc_html__( 'Pin2', 'appart-core'),
        'ti-pin-alt' => esc_html__( 'Pin Alt', 'appart-core'),
        'ti-pencil-alt2' => esc_html__( 'Pencil Alt2', 'appart-core'),
        'ti-palette' => esc_html__( 'Palette', 'appart-core'),
        'ti-more' => esc_html__( 'More', 'appart-core'),
        'ti-more-alt' => esc_html__( 'More Alt', 'appart-core'),
        'ti-microphone-alt' => esc_html__( 'Microphone Alt', 'appart-core'),
        'ti-magnet' => esc_html__( 'Magnet', 'appart-core'),
        'ti-line-double' => esc_html__( 'Line Double', 'appart-core'),
        'ti-line-dotted' => esc_html__( 'Line Dotted', 'appart-core'),
        'ti-line-dashed' => esc_html__( 'Line Dashed', 'appart-core'),
        'ti-layout-width-full' => esc_html__( 'Layout Width Full', 'appart-core'),
        'ti-layout-width-default' => esc_html__( 'Layout Width Default', 'appart-core'),
        'ti-layout-width-default-alt' => esc_html__( 'Layout Width Default Alt', 'appart-core'),
        'ti-layout-tab' => esc_html__( 'Layout Tab', 'appart-core'),
        'ti-layout-tab-window' => esc_html__( 'Layout Tab Window', 'appart-core'),
        'ti-layout-tab-v' => esc_html__( 'Layout Tab V', 'appart-core'),
        'ti-layout-tab-min' => esc_html__( 'Layout Tab Min', 'appart-core'),
        'ti-layout-slider' => esc_html__( 'Layout Slider', 'appart-core'),
        'ti-layout-slider-alt' => esc_html__( 'Layout Slider Alt', 'appart-core'),
        'ti-layout-sidebar-right' => esc_html__( 'Layout Sidebar Right', 'appart-core'),
        'ti-layout-sidebar-none' => esc_html__( 'Layout Sidebar None', 'appart-core'),
        'ti-layout-sidebar-left' => esc_html__( 'Layout Sidebar Left', 'appart-core'),
        'ti-layout-placeholder' => esc_html__( 'Layout Placeholder', 'appart-core'),
        'ti-layout-menu' => esc_html__( 'Layout Menu', 'appart-core'),
        'ti-layout-menu-v' => esc_html__( 'layout Menu V', 'appart-core'),
        'ti-layout-menu-separated' => esc_html__( 'Layout Menu Separated', 'appart-core'),
        'ti-layout-menu-full' => esc_html__( 'Layout Menu Full', 'appart-core'),
        'ti-layout-media-right-alt' => esc_html__( 'Layout Media Right Alt', 'appart-core'),
        'ti-layout-media-right' => esc_html__( 'Layout Media Right', 'appart-core'),
        'ti-layout-media-overlay' => esc_html__( 'Layout Media Overlay', 'appart-core'),
        'ti-layout-media-overlay-alt' => esc_html__( 'Layout Media Overlay Alt', 'appart-core'),
        'ti-layout-media-overlay-alt-2' => esc_html__( 'Layout Media Overlay Alt 2', 'appart-core'),
        'ti-layout-media-left-alt' => esc_html__( 'Layout Media Left Alt', 'appart-core'),
        'ti-layout-media-left' => esc_html__( 'Layout Media Left', 'appart-core'),
        'ti-layout-media-center-alt' => esc_html__( 'Layout Media Center Alt', 'appart-core'),
        'ti-layout-media-center' => esc_html__( 'Layout Media Center', 'appart-core'),
        'ti-layout-list-thumb' => esc_html__( 'Layout List Thumb', 'appart-core'),
        'ti-layout-list-thumb-alt' => esc_html__( 'Layout List Thumb Alt', 'appart-core'),
        'ti-layout-list-post' => esc_html__( 'Layout List Post', 'appart-core'),
        'ti-layout-list-large-image' => esc_html__( 'Layout List Large Image', 'appart-core'),
        'ti-layout-line-solid' => esc_html__( 'Layout Line Solid', 'appart-core'),
        'ti-layout-grid4' => esc_html__( 'Layout Grid4', 'appart-core'),
        'ti-layout-grid3' => esc_html__( 'Layout Grid3', 'appart-core'),
        'ti-layout-grid2' => esc_html__( 'Layout Grid2', 'appart-core'),
        'ti-layout-grid2-thumb' => esc_html__( 'Layout Grid2 Thumb', 'appart-core'),
        'ti-layout-cta-right' => esc_html__( 'Layout Cta Right', 'appart-core'),
        'ti-layout-cta-left' => esc_html__( 'Layout Cta Left', 'appart-core'),
        'ti-layout-cta-center' => esc_html__( 'Layout Cta Center', 'appart-core'),
        'ti-layout-cta-btn-right' => esc_html__( 'Layout Cta Btn Right', 'appart-core'),
        'ti-layout-cta-btn-left' => esc_html__( 'Layout Cta Btn Left', 'appart-core'),
        'ti-layout-column4' => esc_html__( 'Layout Column4', 'appart-core'),
        'ti-layout-column3' => esc_html__( 'Layout Column3', 'appart-core'),
        'ti-layout-column2' => esc_html__( 'Layout Column2', 'appart-core'),
        'ti-layout-accordion-separated' => esc_html__( 'Layout Accordion Separated', 'appart-core'),
        'ti-layout-accordion-merged' => esc_html__( 'Layout Accordion Merged', 'appart-core'),
        'ti-layout-accordion-list' => esc_html__( 'Layout Accordion List', 'appart-core'),
        'ti-ink-pen' => esc_html__( 'Ink Pen', 'appart-core'),
        'ti-info-alt' => esc_html__( 'Info Alt', 'appart-core'),
        'ti-help-alt' => esc_html__( 'Help Alt', 'appart-core'),
        'ti-headphone-alt' => esc_html__( 'Headphone Alt', 'appart-core'),
        'ti-hand-point-up' => esc_html__( 'Hand Point Up', 'appart-core'),
        'ti-hand-point-right' => esc_html__( 'Hand Point Right', 'appart-core'),
        'ti-hand-point-left' => esc_html__( 'Hand Point Left', 'appart-core'),
        'ti-hand-point-down' => esc_html__( 'Hand Point Down', 'appart-core'),
        'ti-gallery' => esc_html__( 'Gallery', 'appart-core'),
        'ti-face-smile' => esc_html__( 'Face Smile', 'appart-core'),
        'ti-face-sad' => esc_html__( 'Face Sad', 'appart-core'),
        'ti-credit-card' => esc_html__( 'Credit Card', 'appart-core'),
        'ti-control-skip-forward' => esc_html__( 'Control Skip Forward', 'appart-core'),
        'ti-control-record' => esc_html__( 'Control Record', 'appart-core'),
        'Control-eject' => esc_html__( 'Control Eject', 'appart-core'),
        'ti-comments-smiley' => esc_html__( 'Comments Smiley', 'appart-core'),
        'ti-brush-alt' => esc_html__( 'Brush Alt', 'appart-core'),
        'ti-youtube' => esc_html__( 'Youtube', 'appart-core'),
        'ti-vimeo' => esc_html__( 'Vimeo', 'appart-core'),
        'ti-twitter' => esc_html__( 'Twitter', 'appart-core'),
        'ti-time' => esc_html__( 'Time', 'appart-core'),
        'ti-tumblr' => esc_html__( 'Tumblr', 'appart-core'),
        'ti-skype' => esc_html__( 'Skype', 'appart-core'),
        'ti-share' => esc_html__( 'Share', 'appart-core'),
        'ti-share-alt' => esc_html__( 'Share Alt', 'appart-core'),
        'ti-rocket' => esc_html__( 'Rocket', 'appart-core'),
        'ti-pinterest' => esc_html__( 'Pinterest', 'appart-core'),
        'ti-new-window' => esc_html__( 'New Window', 'appart-core'),
        'ti-microsoft' => esc_html__( 'Microsoft', 'appart-core'),
        'ti-list-ol' => esc_html__( 'List Ol', 'appart-core'),
        'ti-linkedin' => esc_html__( 'Linkedin', 'appart-core'),
        'ti-layout-sidebar-2' => esc_html__( 'Layout Sidebar-2', 'appart-core'),
        'ti-layout-grid4-alt' => esc_html__( 'Layout Grid4 Alt', 'appart-core'),
        'ti-layout-grid3-alt' => esc_html__( 'Layout Grid3 Alt', 'appart-core'),
        'ti-layout-grid2-alt' => esc_html__( 'Layout Grid2 Alt', 'appart-core'),
        'ti-layout-column4-alt' => esc_html__( 'Layout Column4 Alt', 'appart-core'),
        'ti-layout-column3-alt' => esc_html__( 'Layout Column3 Alt', 'appart-core'),
        'ti-layout-column2-alt' => esc_html__( 'Layout Column2 Alt', 'appart-core'),
        'ti-instagram' => esc_html__( 'Instagram', 'appart-core'),
        'ti-google' => esc_html__( 'Google', 'appart-core'),
        'ti-github' => esc_html__( 'Github', 'appart-core'),
        'ti-flickr' => esc_html__( 'Flickr', 'appart-core'),
        'ti-facebook' => esc_html__( 'Facebook', 'appart-core'),
        'ti-dropbox' => esc_html__( 'Dropbox', 'appart-core'),
        'ti-dribbble' => esc_html__( 'Dribbble', 'appart-core'),
        'ti-apple' => esc_html__( 'Apple', 'appart-core'),
        'ti-android' => esc_html__( 'Android', 'appart-core'),
        'ti-save' => esc_html__( 'Save', 'appart-core'),
        'ti-save-alt' => esc_html__( 'Save Alt', 'appart-core'),
        'ti-yahoo' => esc_html__( 'Yahoo', 'appart-core'),
        'ti-wordpress' => esc_html__( 'Wordpress', 'appart-core'),
        'ti-vimeo-alt' => esc_html__( 'Vimeo Alt', 'appart-core'),
        'ti-twitter-alt' => esc_html__( 'Twitter Alt', 'appart-core'),
        'ti-tumblr-alt' => esc_html__( 'Tumblr Alt', 'appart-core'),
        'ti-trello' => esc_html__( 'Trello', 'appart-core'),
        'ti-stack-overflow' => esc_html__( 'Stack Overflow', 'appart-core'),
        'ti-soundcloud' => esc_html__( 'Soundcloud', 'appart-core'),
        'ti-sharethis' => esc_html__( 'Sharethis', 'appart-core'),
        'ti-sharethis-alt' => esc_html__( 'Sharethis Alt', 'appart-core'),
        'ti-reddit' => esc_html__( 'Reddit', 'appart-core'),
        'ti-pinterest-alt' => esc_html__( 'Pinterest Alt', 'appart-core'),
        'ti-microsoft-alt' => esc_html__( 'Microsoft Alt', 'appart-core'),
        'ti-linux' => esc_html__( 'Linux', 'appart-core'),
        'ti-jsfiddle' => esc_html__( 'Jsfiddle', 'appart-core'),
        'ti-joomla' => esc_html__( 'Joomla', 'appart-core'),
        'ti-html5' => esc_html__( 'Html5', 'appart-core'),
        'ti-flickr-alt' => esc_html__( 'Flickr Alt', 'appart-core'),
        'ti-email' => esc_html__( 'Email', 'appart-core'),
        'ti-drupal' => esc_html__( 'Drupal', 'appart-core'),
        'ti-dropbox-alt' => esc_html__( 'Dropbox Alt', 'appart-core'),
        'ti-css3' => esc_html__( 'Css3', 'appart-core'),
        'ti-rss' => esc_html__( 'Rss', 'appart-core'),
        'ti-rss-alt' => esc_html__( 'Rss-alt', 'appart-core')
    ];
}

function saasland_include_themify_icons() {
    return array_keys(saasland_themify_icons());
}
